### ISSUE TITLE
SETUP MODE: Don't throw Error when `AUTH_API_KEY` is not set

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#48]
At present if the `AUTH_API_KEY` is not set as an environment variable, then `auth_plug` will throw an error. 
e.g: 
```elixir
== Compilation error in file lib/auth_web/router.ex ==
** (RuntimeError) No AUTH_API_KEY set, find out how at: https://git.io/JJ6sS
    (auth_plug 1.4.7) lib/helpers.ex:40: AuthPlug.Helpers.check_environment_vars/0
    (auth_plug 1.4.7) lib/auth_plug.ex:33: AuthPlug.init/1
    (plug 1.12.1) lib/plug/builder.ex:318: Plug.Builder.init_module_plug/4
    (plug 1.12.1) lib/plug/builder.ex:302: anonymous fn/5 in Plug.Builder.compile/3
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug 1.12.1) lib/plug/builder.ex:300: Plug.Builder.compile/3
    lib/auth_web/router.ex:42: (module)
```

It seemed like a good idea at the time we were creating this, because the only time you would see this would be during setup of an app that uses `auth_plug` ... and for that the instructions were pretty clear: https://git.io/JJ6sS 
_However_ on further reflection, while the `AUTH_API_KEY` is not set it means that the App is in "Setup Mode" and shouldn't error. But should inform the person in their terminal _and_ browser that the environment variable is missing. 

Relates to: https://github.com/dwyl/auth/issues/170 Circular Dependency on `auth_plug` in the `auth` App.

**Comment by nelsonic** [comment]
At present the definition of `AuthPlug.Helpers.check_environment_vars/0` has a `raise` when `AUTH_API_KEY` is not set:

https://github.com/dwyl/auth_plug/blob/26ce3b46e454b7aa6cdfc6147b1544753ac109bf/lib/helpers.ex#L32-L44

Instead of the `raise`:
```elixir
raise "No AUTH_API_KEY set, find out how at: https://git.io/JJ6sS"
```

The lack of `AUTH_API_KEY` should be logged to inform the person using `auth_plug` but should still allow their App to start up that way the `auth` app which uses `auth_plug` can still boot and create the "root" (Super Admin) and App.

**Comment by nelsonic** [comment]
Miro-PR created: #49
