### ISSUE TITLE
How to avoid raising an exception when JWT validation fails?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#6]
Stack trace:
```elixir
[info] Sent 500 in 53ms
[error] #PID<0.572.0> running AppWeb.Endpoint (connection #PID<0.571.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /admin
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.atom_to_binary([message: "Invalid token", claim: "exp", claim_val: 1587485301], :utf8)
        (auth_plug 0.2.0) lib/auth_plug.ex:97: AuthPlug.validate_token/3
        (app 0.1.0) AppWeb.Router.auth/2
        (app 0.1.0) lib/app_web/router.ex:1: AppWeb.Router.__pipe_through1__/1
        (phoenix 1.4.16) lib/phoenix/router.ex:283: Phoenix.Router.__call__/2
        (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
        (app 0.1.0) lib/plug/debugger.ex:132: AppWeb.Endpoint."call (overridable 3)"/2
        (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
        (phoenix 1.4.16) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.7.0) /Users/n/code/auth_plug_example/app/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy 2.7.0) /Users/n/code/auth_plug_example/app/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy 2.7.0) /Users/n/code/auth_plug_example/app/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by nelsonic** [comment]
I figured it out. I was trying to run `Atom.to_string()` on value that was occasionally an atom but sometimes a List. I've done `Logger.error(Kernel.inspect(reason))` instead.
